### ISSUE TITLE
Can't click on links in the sidebar when installed

### ISSUE THREAD

**Issue by genandnic** [tom-james-watson/reddit-comment-collapser#24] opened 2020-03-17 18:34 UTC
There's often a lot of useful info and links on the right side of screen when viewing a subreddit. When this plugin is installed, I can't click on any of those links.

**Comment by tom-james-watson** [comment] 2020-03-18 08:31
I've noticed this too, though it doesn't seem to happen all the time. Would need to spend some time looking into it. I have a lot of other things going on right now so it won't be any time soon I'm afraid.

Open to pull requests to address this issue.

**Comment by tom-james-watson** [comment] 2024-04-21 08:02
Closing as a duplicate of https://github.com/tom-james-watson/reddit-comment-collapser/issues/19

**Closed by tom-james-watson** 2024-04-21 08:02 UTC
Labels: bug, contributions wanted
